name: donow
description: "A Nostr native todo list app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  file_saver: ^0.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  get: ^4.7.3
  http: ^1.6.0
  intl: ^0.20.2
  ndk: ^0.6.1-dev.6
  nostr_todo_sdk: ^1.1.2
  nostr_widgets: ^1.1.6
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sembast: ^3.8.6
  sembast_cache_manager: ^1.0.5
  sembast_web: ^2.4.3
  system_theme: ^3.2.0
  toastification: ^3.0.3
  url_launcher: ^6.3.2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
